export interface QuizQuestion {
  id: number
  type: "email" | "chat" | "phone"
  title: string
  content: string
  sender?: string
  isSuspicious: boolean
  explanation: string
}

// Add 50+ questions here. Here are 10 as a sample:
export const questionBank: QuizQuestion[] = [
  {
    id: 1,
    type: "email",
    title: "Urgent Security Alert",
    sender: "security@yourbank.com",
    content: "Your account has been compromised! Click here immediately to secure your account: https://secure-bank-login.net/verify",
    isSuspicious: true,
    explanation: "This is a phishing email. Legitimate banks never ask you to click links in emails to verify accounts.",
  },
  {
    id: 2,
    type: "chat",
    title: "IT Support Request",
    sender: "IT Support",
    content: "Hi! This is John from IT. We're updating our systems and need your password to ensure your account stays active. Can you share it with me?",
    isSuspicious: true,
    explanation: "IT departments never ask for passwords via chat. This is a social engineering attempt.",
  },
  {
    id: 3,
    type: "email",
    title: "Meeting Reminder",
    sender: "calendar@company.com",
    content: "Reminder: Team meeting tomorrow at 2 PM in Conference Room B. Please bring your quarterly reports.",
    isSuspicious: false,
    explanation: "This appears to be a legitimate internal meeting reminder with no suspicious requests.",
  },
  {
    id: 4,
    type: "phone",
    title: "Phone Call Transcript",
    sender: "Unknown Caller",
    content: "Hello, this is Microsoft Support. We've detected malicious activity on your computer. Please download our remote access tool so we can fix it immediately.",
    isSuspicious: true,
    explanation: "Microsoft does not make unsolicited calls. This is a common tech support scam.",
  },
  {
    id: 5,
    type: "email",
    title: "Invoice Notification",
    sender: "billing@company.com",
    content: "Your monthly subscription invoice is ready. Amount due: $29.99. Payment will be automatically processed on the 15th.",
    isSuspicious: false,
    explanation: "This appears to be a standard billing notification with no suspicious elements.",
  },
  // Add more questions here up to 50-100 for variety!
  {
    id: 6,
    type: "chat",
    title: "HR Policy Update",
    sender: "HR Department",
    content: "Please review the attached document for the latest HR policies. Let us know if you have any questions.",
    isSuspicious: false,
    explanation: "This is a typical HR communication with no suspicious requests.",
  },
  {
    id: 7,
    type: "email",
    title: "Password Expiry Notice",
    sender: "admin@company.com",
    content: "Your password will expire in 3 days. Please change it using the official company portal.",
    isSuspicious: false,
    explanation: "Standard password expiry notifications direct you to the official portal.",
  },
  {
    id: 8,
    type: "chat",
    title: "Gift Card Request",
    sender: "CEO",
    content: "Can you buy $500 in gift cards and send me the codes? I'm in a meeting and can't do it myself.",
    isSuspicious: true,
    explanation: "Executives rarely make such requests via chat. This is a common scam.",
  },
  {
    id: 9,
    type: "phone",
    title: "Bank Verification Call",
    sender: "Bank Representative",
    content: "We noticed unusual activity. Please confirm your account number and PIN.",
    isSuspicious: true,
    explanation: "Banks never ask for sensitive info like PINs over the phone.",
  },
  {
    id: 10,
    type: "email",
    title: "Conference Invitation",
    sender: "events@industryconf.com",
    content: "You are invited to speak at our annual conference. Please register using the attached link.",
    isSuspicious: true,
    explanation: "Unsolicited invitations with registration links can be phishing attempts.",
  },
  {
    id: 11,
    type: "email",
    title: "Account Suspension Notice",
    sender: "support@onlineservice.com",
    content: "Your account will be suspended unless you verify your information. Click here to update your details.",
    isSuspicious: true,
    explanation: "Legitimate services do not threaten suspension via unsolicited emails. This is a phishing attempt.",
  },
  {
    id: 12,
    type: "chat",
    title: "Colleague File Share",
    sender: "Jane Doe",
    content: "Hey, can you check this document for me? [suspicious-link.com]",
    isSuspicious: true,
    explanation: "Unexpected file links from colleagues can be phishing attempts.",
  },
  {
    id: 13,
    type: "phone",
    title: "Fake Tax Call",
    sender: "IRS Agent",
    content: "You owe back taxes. Pay now or face legal action.",
    isSuspicious: true,
    explanation: "Tax authorities do not demand payment or threaten arrest over the phone.",
  },
  {
    id: 14,
    type: "email",
    title: "Subscription Renewal",
    sender: "subscriptions@streaming.com",
    content: "Your subscription has been renewed. No action is required.",
    isSuspicious: false,
    explanation: "This is a standard subscription renewal notice.",
  },
  {
    id: 15,
    type: "chat",
    title: "Urgent Request from Manager",
    sender: "Manager",
    content: "I need you to send me the client list ASAP. Don't tell anyone.",
    isSuspicious: true,
    explanation: "Requests for confidential info with secrecy are suspicious.",
  },
  {
    id: 16,
    type: "email",
    title: "Travel Itinerary",
    sender: "travel@company.com",
    content: "Here is your itinerary for the upcoming business trip.",
    isSuspicious: false,
    explanation: "This is a normal business communication.",
  },
  {
    id: 17,
    type: "phone",
    title: "Prize Winner Call",
    sender: "Contest Organizer",
    content: "Congratulations! You've won a car. Pay the processing fee to claim your prize.",
    isSuspicious: true,
    explanation: "Legitimate contests do not require payment to claim prizes.",
  },
  {
    id: 18,
    type: "email",
    title: "Unusual Login Attempt",
    sender: "security@webmail.com",
    content: "We detected a login from a new device. If this wasn't you, reset your password.",
    isSuspicious: false,
    explanation: "Security alerts are common, but always verify the sender and links.",
  },
  {
    id: 19,
    type: "chat",
    title: "Free Software Offer",
    sender: "IT Admin",
    content: "Install this free software to improve your computer's speed.",
    isSuspicious: true,
    explanation: "Unsolicited software offers can be malware.",
  },
  {
    id: 20,
    type: "email",
    title: "Charity Donation Request",
    sender: "charity@helpnow.org",
    content: "Help us support disaster victims. Donate using this link.",
    isSuspicious: true,
    explanation: "Always verify charity requests before donating.",
  },
  {
    id: 21,
    type: "phone",
    title: "Bank Account Locked",
    sender: "Bank Security",
    content: "Your account is locked. Press 1 to unlock.",
    isSuspicious: true,
    explanation: "Banks do not unlock accounts via automated calls.",
  },
  {
    id: 22,
    type: "email",
    title: "Conference Call Details",
    sender: "meetings@company.com",
    content: "Join the conference call at 3 PM using the official link.",
    isSuspicious: false,
    explanation: "This is a standard meeting invite.",
  },
  {
    id: 23,
    type: "chat",
    title: "Password Reset Request",
    sender: "IT Support",
    content: "Click here to reset your password: [malicious-link.com]",
    isSuspicious: true,
    explanation: "Always use official channels for password resets.",
  },
  {
    id: 24,
    type: "email",
    title: "Job Application Received",
    sender: "hr@company.com",
    content: "Thank you for applying. We will contact you soon.",
    isSuspicious: false,
    explanation: "This is a normal HR response.",
  },
  {
    id: 25,
    type: "phone",
    title: "Utility Bill Scam",
    sender: "Electric Company",
    content: "Your electricity will be cut off unless you pay immediately.",
    isSuspicious: true,
    explanation: "Utility companies do not threaten immediate disconnection over the phone.",
  },
  {
    id: 26,
    type: "email",
    title: "Social Media Alert",
    sender: "alerts@socialmedia.com",
    content: "Someone tried to log in to your account. If this wasn't you, secure your account.",
    isSuspicious: false,
    explanation: "This is a typical security alert.",
  },
  {
    id: 27,
    type: "chat",
    title: "Unusual Request",
    sender: "Coworker",
    content: "Can you send me the payroll files? My access isn't working.",
    isSuspicious: true,
    explanation: "Verify unusual requests for sensitive information.",
  },
  {
    id: 28,
    type: "email",
    title: "Order Confirmation",
    sender: "orders@onlineshop.com",
    content: "Your order has been shipped. Track your package here.",
    isSuspicious: false,
    explanation: "This is a standard order confirmation.",
  },
  {
    id: 29,
    type: "phone",
    title: "Fake Police Call",
    sender: "Police Department",
    content: "You are under investigation. Pay a fine to avoid arrest.",
    isSuspicious: true,
    explanation: "Police do not demand payment over the phone.",
  },
  {
    id: 30,
    type: "email",
    title: "Internal Survey",
    sender: "survey@company.com",
    content: "Please complete this internal survey by Friday.",
    isSuspicious: false,
    explanation: "This is a normal internal communication.",
  },
  {
    id: 31,
    type: "email",
    title: "Fake Invoice Attached",
    sender: "accounts@vendor.com",
    content: "Please see the attached invoice for your recent purchase. Contact us if you have questions.",
    isSuspicious: true,
    explanation: "Unexpected invoices with attachments can be phishing or malware.",
  },
  {
    id: 32,
    type: "chat",
    title: "Quick Favor Needed",
    sender: "Director",
    content: "Can you send me your mobile number? I lost my phone.",
    isSuspicious: true,
    explanation: "Always verify identity before sharing personal info.",
  },
  {
    id: 33,
    type: "phone",
    title: "Fake Tech Support",
    sender: "Tech Support",
    content: "We detected a virus on your computer. Please provide your login credentials.",
    isSuspicious: true,
    explanation: "Tech support never asks for passwords.",
  },
  {
    id: 34,
    type: "email",
    title: "Password Change Confirmation",
    sender: "no-reply@company.com",
    content: "Your password was changed successfully. If this wasn't you, contact support.",
    isSuspicious: false,
    explanation: "This is a standard notification.",
  },
  {
    id: 35,
    type: "chat",
    title: "Lunch Order",
    sender: "Reception",
    content: "What would you like for lunch today?",
    isSuspicious: false,
    explanation: "This is a normal workplace message.",
  },
  {
    id: 36,
    type: "email",
    title: "Unclaimed Package",
    sender: "delivery@courier.com",
    content: "You have a package waiting. Click here to schedule delivery.",
    isSuspicious: true,
    explanation: "Unexpected delivery emails with links can be phishing.",
  },
  {
    id: 37,
    type: "phone",
    title: "Fake Jury Duty",
    sender: "Court Clerk",
    content: "You missed jury duty. Pay a fine now to avoid arrest.",
    isSuspicious: true,
    explanation: "Courts do not demand payment over the phone.",
  },
  {
    id: 38,
    type: "email",
    title: "Payroll Update",
    sender: "payroll@company.com",
    content: "Your salary has been updated. View your new payslip online.",
    isSuspicious: false,
    explanation: "This is a normal payroll notification.",
  },
  {
    id: 39,
    type: "chat",
    title: "Strange Link",
    sender: "Friend",
    content: "Check out this cool video! [random-link.com]",
    isSuspicious: true,
    explanation: "Unexpected links from friends can be compromised accounts.",
  },
  {
    id: 40,
    type: "email",
    title: "Fake Refund",
    sender: "refunds@onlineshop.com",
    content: "You are eligible for a refund. Enter your bank details to proceed.",
    isSuspicious: true,
    explanation: "Legitimate companies do not ask for bank details via email.",
  },
  {
    id: 41,
    type: "phone",
    title: "Fake Insurance Call",
    sender: "Insurance Agent",
    content: "Your policy is expiring. Pay now to avoid losing coverage.",
    isSuspicious: true,
    explanation: "Insurance companies send official notices, not urgent calls.",
  },
  {
    id: 42,
    type: "email",
    title: "Conference Room Booking",
    sender: "facilities@company.com",
    content: "Your conference room is booked for tomorrow at 10 AM.",
    isSuspicious: false,
    explanation: "This is a standard facilities notification.",
  },
  {
    id: 43,
    type: "chat",
    title: "Unusual IT Request",
    sender: "IT Support",
    content: "Can you disable your antivirus for a few minutes?",
    isSuspicious: true,
    explanation: "IT should never ask you to disable security software.",
  },
  {
    id: 44,
    type: "email",
    title: "Fake Survey",
    sender: "survey@unknown.com",
    content: "Complete this survey and win a prize!",
    isSuspicious: true,
    explanation: "Unsolicited surveys promising prizes are often scams.",
  },
  {
    id: 45,
    type: "phone",
    title: "Fake Bank Call",
    sender: "Bank",
    content: "We need to verify your account. Please provide your full card number.",
    isSuspicious: true,
    explanation: "Banks never ask for full card numbers over the phone.",
  },
  {
    id: 46,
    type: "email",
    title: "Welcome to the Team",
    sender: "hr@company.com",
    content: "Welcome aboard! Here are your onboarding documents.",
    isSuspicious: false,
    explanation: "This is a standard HR welcome message.",
  },
  {
    id: 47,
    type: "chat",
    title: "Suspicious File",
    sender: "Coworker",
    content: "Can you open this file for me? My computer can't read it.",
    isSuspicious: true,
    explanation: "Unexpected file requests can be phishing.",
  },
  {
    id: 48,
    type: "email",
    title: "Fake Tax Refund",
    sender: "taxrefund@irs.gov",
    content: "You are eligible for a tax refund. Click here to claim.",
    isSuspicious: true,
    explanation: "Tax authorities do not send unsolicited refund emails.",
  },
  {
    id: 49,
    type: "phone",
    title: "Fake Family Emergency",
    sender: "Unknown",
    content: "This is the hospital. Your relative is here. Send money for treatment.",
    isSuspicious: true,
    explanation: "Hospitals do not demand money over the phone.",
  },
  {
    id: 50,
    type: "email",
    title: "System Maintenance",
    sender: "it@company.com",
    content: "Scheduled maintenance will occur this weekend.",
    isSuspicious: false,
    explanation: "This is a normal IT notification.",
  },
  {
    id: 51,
    type: "chat",
    title: "Unusual Payment Request",
    sender: "Finance",
    content: "Can you process this urgent payment to a new vendor?",
    isSuspicious: true,
    explanation: "Urgent payment requests should always be verified.",
  },
  {
    id: 52,
    type: "email",
    title: "Fake Account Recovery",
    sender: "recovery@webmail.com",
    content: "Your account is locked. Click here to recover.",
    isSuspicious: true,
    explanation: "Always use official sites for account recovery.",
  },
  {
    id: 53,
    type: "phone",
    title: "Fake Lottery Win",
    sender: "Lottery Office",
    content: "You've won the lottery! Pay a fee to claim your prize.",
    isSuspicious: true,
    explanation: "Legitimate lotteries do not require payment to claim winnings.",
  },
  {
    id: 54,
    type: "email",
    title: "Company Newsletter",
    sender: "newsletter@company.com",
    content: "Here is your monthly company newsletter.",
    isSuspicious: false,
    explanation: "This is a standard newsletter.",
  },
  {
    id: 55,
    type: "chat",
    title: "Suspicious Link",
    sender: "Friend",
    content: "Look at this! [phishing-link.com]",
    isSuspicious: true,
    explanation: "Unexpected links can be phishing.",
  },
  {
    id: 56,
    type: "email",
    title: "Fake Legal Notice",
    sender: "legal@unknown.com",
    content: "You are being sued. Click here for details.",
    isSuspicious: true,
    explanation: "Legal notices are not sent via email links.",
  },
  {
    id: 57,
    type: "phone",
    title: "Fake Tech Refund",
    sender: "Tech Company",
    content: "We owe you a refund. Please provide your bank details.",
    isSuspicious: true,
    explanation: "Legitimate companies do not ask for bank info over the phone.",
  },
  {
    id: 58,
    type: "email",
    title: "Password Reset Success",
    sender: "no-reply@company.com",
    content: "Your password was reset. If this wasn't you, contact support.",
    isSuspicious: false,
    explanation: "This is a standard password reset notification.",
  },
  {
    id: 59,
    type: "chat",
    title: "Unusual Gift Card Request",
    sender: "Boss",
    content: "Buy $200 in gift cards and send me the codes.",
    isSuspicious: true,
    explanation: "Gift card requests are a common scam.",
  },
  {
    id: 60,
    type: "email",
    title: "Fake Social Media Alert",
    sender: "security@socialmedia.com",
    content: "Your account will be deleted. Click here to prevent this.",
    isSuspicious: true,
    explanation: "Social media platforms do not threaten deletion via email.",
  },
  {
    id: 61,
    type: "phone",
    title: "Fake Medical Bill",
    sender: "Hospital Billing",
    content: "You owe money for a recent procedure. Pay now.",
    isSuspicious: true,
    explanation: "Hospitals send official bills, not urgent calls.",
  },
  {
    id: 62,
    type: "email",
    title: "Annual Benefits Enrollment",
    sender: "benefits@company.com",
    content: "It's time to enroll in your annual benefits.",
    isSuspicious: false,
    explanation: "This is a standard HR communication.",
  },
  {
    id: 63,
    type: "chat",
    title: "Fake IT Alert",
    sender: "IT Support",
    content: "Your computer is infected. Download this tool.",
    isSuspicious: true,
    explanation: "IT will never ask you to download unknown tools.",
  },
  {
    id: 64,
    type: "email",
    title: "Fake Shipping Notice",
    sender: "shipping@unknown.com",
    content: "Your package is delayed. Click here for details.",
    isSuspicious: true,
    explanation: "Shipping companies do not send unsolicited links.",
  },
  {
    id: 65,
    type: "phone",
    title: "Fake Student Loan Call",
    sender: "Loan Officer",
    content: "Your loan is overdue. Pay now to avoid penalties.",
    isSuspicious: true,
    explanation: "Loan companies send official notices, not urgent calls.",
  },
  {
    id: 66,
    type: "email",
    title: "Employee Satisfaction Survey",
    sender: "hr@company.com",
    content: "Please complete this anonymous survey.",
    isSuspicious: false,
    explanation: "This is a normal HR survey.",
  },
  {
    id: 67,
    type: "chat",
    title: "Fake Account Verification",
    sender: "Support",
    content: "We need to verify your account. Send your password.",
    isSuspicious: true,
    explanation: "Support never asks for passwords.",
  },
  {
    id: 68,
    type: "email",
    title: "Fake App Store Receipt",
    sender: "appstore@unknown.com",
    content: "You have been charged $99.99. Click here to dispute.",
    isSuspicious: true,
    explanation: "App stores do not send dispute links via email.",
  },
  {
    id: 69,
    type: "phone",
    title: "Fake Charity Call",
    sender: "Charity",
    content: "Donate now to help disaster victims.",
    isSuspicious: true,
    explanation: "Always verify charity calls.",
  },
  {
    id: 70,
    type: "email",
    title: "Welcome Email",
    sender: "welcome@company.com",
    content: "Welcome to the company! Let us know if you have questions.",
    isSuspicious: false,
    explanation: "This is a standard welcome email.",
  },
  {
    id: 71,
    type: "chat",
    title: "Fake Security Alert",
    sender: "Security Team",
    content: "Your account is at risk. Send your credentials to secure it.",
    isSuspicious: true,
    explanation: "Security teams never ask for credentials.",
  },
  {
    id: 72,
    type: "email",
    title: "Fake Bank Statement",
    sender: "bank@unknown.com",
    content: "Your monthly statement is attached. Open the file to view.",
    isSuspicious: true,
    explanation: "Unexpected attachments from banks can be malware.",
  },
  {
    id: 73,
    type: "phone",
    title: "Fake Government Grant",
    sender: "Government Agency",
    content: "You qualify for a grant. Pay a fee to receive it.",
    isSuspicious: true,
    explanation: "Government grants do not require payment.",
  },
  {
    id: 74,
    type: "email",
    title: "Fake Job Offer",
    sender: "recruiter@unknown.com",
    content: "We reviewed your resume. Click here to accept the job.",
    isSuspicious: true,
    explanation: "Unsolicited job offers with links are suspicious.",
  },
  {
    id: 75,
    type: "chat",
    title: "Fake Account Update",
    sender: "Admin",
    content: "Update your account info here: [phishing-link.com]",
    isSuspicious: true,
    explanation: "Admins never send update links via chat.",
  },
  {
    id: 76,
    type: "email",
    title: "Fake Payment Request",
    sender: "payments@unknown.com",
    content: "Please pay the attached invoice immediately.",
    isSuspicious: true,
    explanation: "Unexpected payment requests are suspicious.",
  },
  {
    id: 77,
    type: "phone",
    title: "Fake Immigration Call",
    sender: "Immigration Officer",
    content: "Your visa is expiring. Pay now to renew.",
    isSuspicious: true,
    explanation: "Immigration offices do not demand payment over the phone.",
  },
  {
    id: 78,
    type: "email",
    title: "Fake Password Expiry",
    sender: "admin@unknown.com",
    content: "Your password expires today. Click here to reset.",
    isSuspicious: true,
    explanation: "Always use official sites for password changes.",
  },
  {
    id: 79,
    type: "chat",
    title: "Fake IT Survey",
    sender: "IT Department",
    content: "Complete this survey to keep your account active.",
    isSuspicious: true,
    explanation: "IT does not require surveys for account activity.",
  },
  {
    id: 80,
    type: "email",
    title: "Fake Delivery Notice",
    sender: "delivery@unknown.com",
    content: "Your package is waiting. Click here to claim.",
    isSuspicious: true,
    explanation: "Unexpected delivery notices are suspicious.",
  },
  {
    id: 81,
    type: "phone",
    title: "Fake Health Insurance Call",
    sender: "Health Insurance",
    content: "Your policy is expiring. Pay now to renew.",
    isSuspicious: true,
    explanation: "Health insurance companies send official notices.",
  },
  {
    id: 82,
    type: "email",
    title: "Fake Account Locked",
    sender: "support@unknown.com",
    content: "Your account is locked. Click here to unlock.",
    isSuspicious: true,
    explanation: "Always use official channels for account issues.",
  },
  {
    id: 83,
    type: "chat",
    title: "Fake HR Request",
    sender: "HR",
    content: "Send your SSN for our records.",
    isSuspicious: true,
    explanation: "HR never asks for sensitive info via chat.",
  },
  {
    id: 84,
    type: "email",
    title: "Fake Conference Invite",
    sender: "events@unknown.com",
    content: "Join our conference. Register here.",
    isSuspicious: true,
    explanation: "Unsolicited invites with links are suspicious.",
  },
  {
    id: 85,
    type: "phone",
    title: "Fake Bank Fraud Alert",
    sender: "Bank Fraud Dept",
    content: "We detected fraud. Provide your PIN to secure your account.",
    isSuspicious: true,
    explanation: "Banks never ask for PINs.",
  },
  {
    id: 86,
    type: "email",
    title: "Fake App Update",
    sender: "app@unknown.com",
    content: "Update your app now. Click here to download.",
    isSuspicious: true,
    explanation: "App updates should be done via official stores.",
  },
  {
    id: 87,
    type: "chat",
    title: "Fake Payroll Update",
    sender: "Payroll",
    content: "Send your bank details for payroll update.",
    isSuspicious: true,
    explanation: "Payroll updates are handled via secure portals.",
  },
  {
    id: 88,
    type: "email",
    title: "Fake Security Patch",
    sender: "security@unknown.com",
    content: "Install this patch to secure your computer.",
    isSuspicious: true,
    explanation: "Security patches should come from official sources.",
  },
  {
    id: 89,
    type: "phone",
    title: "Fake Student Grant",
    sender: "Student Services",
    content: "You qualify for a grant. Pay a fee to receive it.",
    isSuspicious: true,
    explanation: "Student grants do not require payment.",
  },
  {
    id: 90,
    type: "email",
    title: "Fake Account Verification",
    sender: "verify@unknown.com",
    content: "Verify your account by clicking this link.",
    isSuspicious: true,
    explanation: "Always verify sender and links.",
  },
  {
    id: 91,
    type: "chat",
    title: "Fake IT Credentials Request",
    sender: "IT",
    content: "Send your username and password for maintenance.",
    isSuspicious: true,
    explanation: "IT never asks for credentials.",
  },
  {
    id: 92,
    type: "email",
    title: "Fake Payment Confirmation",
    sender: "payments@unknown.com",
    content: "Your payment was received. Click here for your receipt.",
    isSuspicious: true,
    explanation: "Unexpected payment confirmations are suspicious.",
  },
  {
    id: 93,
    type: "phone",
    title: "Fake Travel Agency",
    sender: "Travel Agency",
    content: "Your trip is canceled. Pay a fee to reschedule.",
    isSuspicious: true,
    explanation: "Travel agencies do not demand payment over the phone.",
  },
  {
    id: 94,
    type: "email",
    title: "Fake Document Signature",
    sender: "sign@unknown.com",
    content: "Sign this document to complete your application.",
    isSuspicious: true,
    explanation: "Unexpected signature requests are suspicious.",
  },
  {
    id: 95,
    type: "chat",
    title: "Fake CEO Request",
    sender: "CEO",
    content: "Wire money to this account immediately.",
    isSuspicious: true,
    explanation: "Verify all urgent financial requests.",
  },
  {
    id: 96,
    type: "email",
    title: "Fake Account Activity",
    sender: "alerts@unknown.com",
    content: "Unusual activity detected. Click here to review.",
    isSuspicious: true,
    explanation: "Always use official sites to check account activity.",
  },
  {
    id: 97,
    type: "phone",
    title: "Fake Delivery Fee",
    sender: "Courier",
    content: "Pay a fee to receive your package.",
    isSuspicious: true,
    explanation: "Couriers do not demand payment over the phone.",
  },
  {
    id: 98,
    type: "email",
    title: "Fake IT Maintenance",
    sender: "it@unknown.com",
    content: "We need your password for scheduled maintenance.",
    isSuspicious: true,
    explanation: "IT never asks for passwords.",
  },
  {
    id: 99,
    type: "chat",
    title: "Fake HR Survey",
    sender: "HR",
    content: "Complete this survey to keep your job.",
    isSuspicious: true,
    explanation: "HR does not threaten employment via surveys.",
  },
  {
    id: 100,
    type: "email",
    title: "Fake Account Upgrade",
    sender: "upgrade@unknown.com",
    content: "Upgrade your account now. Click here.",
    isSuspicious: true,
    explanation: "Account upgrades should be done via official channels.",
  },
]
/**
 * Returns a random set of questions, avoiding repeats until all are used.
 */
let usedIds = new Set<number>()
export function getRandomQuestions(count: number): QuizQuestion[] {
  let available = questionBank.filter(q => !usedIds.has(q.id))
  if (available.length < count) {
    usedIds.clear()
    available = [...questionBank]
  }
  const shuffled = available.sort(() => Math.random() - 0.5)
  const selected = shuffled.slice(0, count)
  selected.forEach(q => usedIds.add(q.id))
  return selected
}